package ifc

import (
	"encoding/json"
	"math"
	"os"
	"testing"

	"github.com/blox-eng/common/ifc/step"
)

// oracleElem is one node of the committed import_emit.py baseline (trimmed to the
// contract-critical fields). Generated by running the Python emitter on kb645; see
// testdata/oracle/kb645_import.json.
type oracleElem struct {
	GlobalID   string             `json:"global_id"`
	IFCClass   string             `json:"ifc_class"`
	ParentGID  *string            `json:"parent_gid"`
	Dimensions map[string]float64 `json:"dimensions"`
}

// TestImportContract_KB645 diffs BuildImport against the real import_emit.py
// baseline. It ASSERTS the contract-critical invariants that must hold exactly:
//
//	set parity        — same GlobalId set (no missing / extra nodes)
//	spatial tree      — every node's parent (by GlobalId) matches Python
//	tier-1 quantities — authored Qto (quantity_source=="qto") matches exactly
//
// Tier-2 (geometry-derived) dimensions are DOCUMENTED-divergent and NOT asserted:
// Python derives area/volume/perimeter from the REAL tessellated mesh
// (ushape.get_max_side_area / get_volume / get_footprint_perimeter), whereas the
// Go engine derives them from the proxy world-AABB (box footprint/volume/perimeter).
// These are different quantities by construction (length/width/height agree — both
// AABB). They land in object_geometry.dimensions (display metadata), NOT in the
// pricing path (recipes + reported quantities), so the divergence does not move
// prices. The magnitudes are logged for visibility. Self-skips without the
// gitignored kb645 corpus.
func TestImportContract_KB645(t *testing.T) {
	const ifcPath = "step/testdata/real/kb645.ifc"
	if _, err := os.Stat(ifcPath); err != nil {
		t.Skip("no kb645.ifc corpus; skipping import-contract gate")
	}
	f, err := step.ParseFile(ifcPath)
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	m, err := BuildImport(f)
	if err != nil {
		t.Fatalf("BuildImport: %v", err)
	}

	raw, err := os.ReadFile("testdata/oracle/kb645_import.json")
	if err != nil {
		t.Fatalf("read oracle: %v", err)
	}
	var oracle struct {
		Elements []oracleElem `json:"elements"`
	}
	if err := json.Unmarshal(raw, &oracle); err != nil {
		t.Fatalf("decode oracle: %v", err)
	}
	oByGID := make(map[string]oracleElem, len(oracle.Elements))
	for _, e := range oracle.Elements {
		oByGID[e.GlobalID] = e
	}
	goByGID := make(map[string]int, len(m.Nodes))
	for i := range m.Nodes {
		goByGID[m.Nodes[i].GlobalID] = i
	}

	// --- set parity ---
	var missing, extra int
	for gid := range oByGID {
		if _, ok := goByGID[gid]; !ok {
			missing++
		}
	}
	for gid := range goByGID {
		if _, ok := oByGID[gid]; !ok {
			extra++
		}
	}
	if missing != 0 || extra != 0 {
		t.Errorf("set parity broken: missing=%d extra=%d (go=%d oracle=%d)", missing, extra, len(m.Nodes), len(oracle.Elements))
	}

	// --- spatial tree parity (parent by GlobalId) + tier-1 quantities ---
	var parentMismatch, tier1Mismatch, tier2N int
	tier2 := map[string]int{} // dim -> count of >1% divergences (informational)
	for i := range m.Nodes {
		n := m.Nodes[i]
		o, ok := oByGID[n.GlobalID]
		if !ok {
			continue
		}
		var goParentGID *string
		if n.ParentIndex != nil {
			g := m.Nodes[*n.ParentIndex].GlobalID
			goParentGID = &g
		}
		if !eqStrPtr(goParentGID, o.ParentGID) {
			parentMismatch++
			if parentMismatch <= 5 {
				t.Errorf("parent mismatch for %s (%s): go=%v oracle=%v", n.GlobalID, n.IFCClass, deref(goParentGID), deref(o.ParentGID))
			}
		}

		goDims := map[string]float64{
			"area": qval(n.Qto.Area), "volume": qval(n.Qto.Volume), "length": qval(n.Qto.Length),
			"width": qval(n.Qto.Width), "height": qval(n.Qto.Height), "perimeter": qval(n.Qto.Perimeter),
		}
		for dim, gv := range goDims {
			ov := o.Dimensions[dim]
			if n.QuantitySource == "qto" {
				// authored tier-1 must match exactly (oracle rounded to 4dp).
				if math.Abs(gv-ov) > 1e-2 {
					tier1Mismatch++
					if tier1Mismatch <= 5 {
						t.Errorf("tier-1 %s.%s = %.4f oracle %.4f", n.GlobalID, dim, gv, ov)
					}
				}
			} else {
				if dim == "area" {
					tier2N++ // count geometry-tier elements once
				}
				den := math.Max(math.Abs(ov), 1e-3)
				if math.Abs(gv-ov)/den > 0.01 && math.Abs(gv-ov) > 1e-3 {
					tier2[dim]++
				}
			}
		}
	}

	// Tier-2 regression floor: mesh-derived area/perimeter (ifcopenshell parity)
	// match Python EXACTLY for brep-passthrough elements (the majority) and only
	// diverge on genuine extrude/OBB proxies. If someone reverts to AABB-derived
	// quantities the match rate collapses toward zero — this floor catches that.
	if tier2N > 0 {
		for _, dim := range []string{"area", "perimeter"} {
			matched := tier2N - tier2[dim]
			if frac := float64(matched) / float64(tier2N); frac < 0.5 {
				t.Errorf("tier-2 %s match rate %.0f%% (%d/%d within 1%%) below 50%% floor — mesh-quantity wiring regressed?", dim, frac*100, matched, tier2N)
			}
		}
	}

	if parentMismatch != 0 {
		t.Errorf("spatial tree parity: %d parent mismatches", parentMismatch)
	}
	if tier1Mismatch != 0 {
		t.Errorf("tier-1 (authored Qto) parity: %d mismatches", tier1Mismatch)
	}
	t.Logf("CONTRACT GATE: set OK (go=%d), tree OK, tier-1 OK. tier-2 (proxy-AABB vs Python-mesh, metadata-only) divergences >1%%: %v", len(m.Nodes), tier2)
}

func eqStrPtr(a, b *string) bool {
	if (a == nil) != (b == nil) {
		return false
	}
	return a == nil || *a == *b
}

func qval(p *float64) float64 {
	if p != nil {
		return *p
	}
	return 0
}

func deref(p *string) string {
	if p == nil {
		return "<root>"
	}
	return *p
}
