package parity

import (
	"fmt"
	"sort"
	"strings"

	"github.com/blox-eng/goifc/geometry"
	"github.com/blox-eng/goifc/model"
)

// Report renders the published coverage page. Its content is generated, never
// hand-edited: a stale accuracy number is worse than no number.
//
// It covers only the public corpus (Public): Load prefers a private model
// over its committed fixture when $GOIFC_PRIVATE_CORPUS is set, so ranging
// over anything beyond Public would make the generated page depend on which
// private files happen to be on disk. That would fail `-check` for anyone
// holding those files, through no fault of theirs.
func Report() (string, error) {
	var b strings.Builder
	b.WriteString("# Coverage\n\n")
	b.WriteString("How much of a real IFC model goifc tessellates, and how loose\n")
	b.WriteString("its bounds are against IfcOpenShell. Measured against the public\n")
	b.WriteString("corpus only ([`parity.Public`](https://github.com/blox-eng/goifc/blob/main/parity/corpus.go)).\n")
	b.WriteString("Generated by `make parity-report` — do not edit by hand.\n\n")

	b.WriteString("The **OBB rate** is the number with real signal: it is the share of\n")
	b.WriteString("elements that produced geometry but fell back to a bounding box\n")
	b.WriteString("instead of a tessellated shape. The **looseness** columns compare\n")
	b.WriteString("goifc's world AABB to IfcOpenShell's world AABB — not to the true\n")
	b.WriteString("solid, which the oracle does not store. Those two boxes are\n")
	b.WriteString("near-identical for any element both engines tessellate at all,\n")
	b.WriteString("including one that fell back to an OBB on both sides, so a ratio\n")
	b.WriteString("of 1.00 here is nearly blind to fallback quality by construction —\n")
	b.WriteString("read it as \"box vs. box\", not as \"goifc matches IfcOpenShell\".\n")
	b.WriteString("Ratios are printed to four decimal places so \"exactly 1\" and\n")
	b.WriteString("\"very close to 1\" are distinguishable.\n\n")

	b.WriteString("| Model | Elements | Extrude | Brep | OBB | Empty | OBB rate | AABB ratio p50 | p90 | max |\n")
	b.WriteString("|---|---|---|---|---|---|---|---|---|---|\n")
	for _, name := range Public {
		c, err := MeasureCoverage(name)
		if err != nil {
			return "", err
		}
		l, err := MeasureLooseness(name)
		if err != nil {
			return "", err
		}
		fmt.Fprintf(&b, "| `%s` | %d | %d | %d | %d | %d | %.1f%% | %.4f | %.4f | %.4f |\n",
			name, c.Total, c.Extrude, c.Brep, c.OBB, c.Empty, 100*OBBRate(c), l.P50, l.P90, l.Max)
	}

	b.WriteString("\n## What falls back, and how often\n\n")
	b.WriteString("Representation-item types with no tessellation path. ")
	b.WriteString("Closing the top of this list buys the most accuracy.\n\n")
	b.WriteString("Counts are OCCURRENCES, not distinct entities: an `IfcMappedItem`\n")
	b.WriteString("is resolved to the items it maps, and each resolution is counted\n")
	b.WriteString("again — once per element that reaches it. A family placed many\n")
	b.WriteString("times via one `IfcRepresentationMap` costs accuracy every time it\n")
	b.WriteString("is placed, so it must rank every time, not once. This means a\n")
	b.WriteString("type's count can legitimately exceed the number of entities of\n")
	b.WriteString("that type in the file — for example, `duplex_a` reports 65\n")
	b.WriteString("occurrences of `IFCFACEBASEDSURFACEMODEL` from 40 such entities\n")
	b.WriteString("in the file. Keys are the upper-case STEP keyword as parsed\n")
	b.WriteString("(`IFCFACEBASEDSURFACEMODEL`, not `IfcFaceBasedSurfaceModel`);\n")
	b.WriteString("nothing here changes that casing.\n\n")
	b.WriteString("| Item type | Occurrences |\n|---|---|\n")

	totals := map[string]int{}
	for _, name := range Public {
		f, err := Load(name)
		if err != nil {
			return "", err
		}
		r, err := model.Extract(f)
		if err != nil {
			return "", err
		}
		for ty, n := range geometry.UnhandledItemTypes(f, r) {
			totals[ty] += n
		}
	}
	types := make([]string, 0, len(totals))
	for ty := range totals {
		types = append(types, ty)
	}
	sort.Slice(types, func(i, j int) bool {
		if totals[types[i]] != totals[types[j]] {
			return totals[types[i]] > totals[types[j]]
		}
		return types[i] < types[j]
	})
	if len(types) == 0 {
		b.WriteString("| _none_ | 0 |\n")
	}
	for _, ty := range types {
		fmt.Fprintf(&b, "| `%s` | %d |\n", ty, totals[ty])
	}

	b.WriteString("\n## Known Gate 1 violations\n\n")
	b.WriteString("Gate 1 asserts that goifc's AABB contains IfcOpenShell's oracle box\n")
	b.WriteString("for every element the oracle knows. Against `duplex_a`, the gate\n")
	b.WriteString("compares 215 elements. All but two are contained. The two are the\n")
	b.WriteString("same Revit stair type (\"Stair:Residential - 200mm Max Riser 250mm\n")
	b.WriteString("Tread\", 16 risers / 15 treads) placed twice — `IfcStairFlight`\n")
	b.WriteString("instances `1oKjKg9PD3fP1iIwXLh3lK` and `3KMJUyUe9DfQ2FOCd5ZoiN` —\n")
	b.WriteString("whose goifc world AABB is smaller than IfcOpenShell's by about\n")
	b.WriteString("0.99 cm on the Y axis (0.009927508 m and 0.009927222 m). A bound\n")
	b.WriteString("that under-reports is always a bug, never a legitimate fallback:\n")
	b.WriteString("this is a real, currently open goifc geometry gap, tracked in\n")
	b.WriteString("`parity/parity_test.go`'s `knownViolations` allowlist so CI stays\n")
	b.WriteString("green on this known state while still failing on any new or\n")
	b.WriteString("worsened violation.\n")

	return b.String(), nil
}
