package parity

import (
	"fmt"
	"sort"
	"strings"

	"github.com/blox-eng/goifc/geometry"
	"github.com/blox-eng/goifc/model"
)

// Report renders the published coverage page. Its content is generated, never
// hand-edited: a stale accuracy number is worse than no number.
//
// It covers only the public corpus (Public): Load prefers a private model
// over its committed fixture when $GOIFC_PRIVATE_CORPUS is set, so ranging
// over anything beyond Public would make the generated page depend on which
// private files happen to be on disk. That would fail `-check` for anyone
// holding those files, through no fault of theirs.
func Report() (string, error) {
	// Measured first, because the prose below states how many shortfalls the
	// page records and that number must be the measurement, not len(allowlist).
	// Gate 1 skips an allowlisted element absent from the scene, and the
	// per-model sections below are gated on measured state, so a stale entry
	// would have the opening sentence promising a table that is not printed.
	per, totalCompared, totalContained, err := measureGate1()
	if err != nil {
		return "", err
	}
	shortfalls := totalCompared - totalContained

	var b strings.Builder
	b.WriteString("# Coverage\n\n")
	b.WriteString("How much of a real IFC model goifc tessellates, and how loose\n")
	b.WriteString("its bounds are against IfcOpenShell. Measured against the public\n")
	b.WriteString("corpus only ([`parity.Public`](https://github.com/blox-eng/goifc/blob/main/parity/corpus.go)).\n")
	b.WriteString("Generated by `make parity-report` — do not edit by hand.\n\n")

	b.WriteString("The **OBB rate** is the number with real signal: it is the share of\n")
	b.WriteString("elements that produced geometry but fell back to a bounding box\n")
	b.WriteString("instead of a tessellated shape. The **looseness** columns compare\n")
	b.WriteString("goifc's world AABB to IfcOpenShell's world AABB — not to the true\n")
	b.WriteString("solid, which the oracle does not store. Those two boxes are\n")
	b.WriteString("near-identical for any element both engines tessellate. For one\n")
	b.WriteString("that fell back to goifc's own OBB path, the box is built from the\n")
	b.WriteString("`IfcCartesianPoint` coordinates reachable from the element's\n")
	b.WriteString("representation, so it coincides with the true solid's world AABB\n")
	b.WriteString("only where those points reach the solid's extremes. Where they do\n")
	b.WriteString("not — a revolved or otherwise curved sweep has extremes that no\n")
	b.WriteString("point in the file names — the fallback box can come out either\n")
	b.WriteString("looser than the true solid (a pitched roof's OBB can hold twice\n")
	b.WriteString("its volume) or, the failure that actually hurts a consumer,\n")
	b.WriteString("tighter than it. Gate 1 is precisely what catches the tighter\n")
	b.WriteString("case — and an under-reporting bound wherever else one arises.\n")
	fmt.Fprintf(&b, "All %d of the shortfalls recorded below are Gate 1 firing on a\n", shortfalls)
	b.WriteString("different cause, not on a fallback box: those elements\n")
	b.WriteString("tessellate through the extrusion path, and\n")
	b.WriteString("`parity/knownviolations.go` attributes their shortfall to how\n")
	b.WriteString("goifc bounds a stepped solid along that path.\n")
	b.WriteString("(IfcOpenShell has no OBB fallback of its own — its oracle boxes\n")
	b.WriteString("come from an exact-solid tessellation.) So a ratio of 1.00 here is\n")
	b.WriteString("nearly blind to fallback quality by construction — read it as\n")
	b.WriteString("\"box vs. box\", not as \"goifc matches IfcOpenShell\".\n")
	b.WriteString("Ratios are printed to four decimal places so \"exactly 1\" and\n")
	b.WriteString("\"very close to 1\" are distinguishable.\n")
	b.WriteString("**Collapsed** is elements excluded from the ratio columns because\n")
	b.WriteString("goifc's own box has zero volume — flat, inverted, or empty. Their\n")
	b.WriteString("ratio would be exactly 0, a well-formed number for the worst\n")
	b.WriteString("possible outcome, which would drag p50 and p90 toward 1.0 and read\n")
	b.WriteString("as an improvement. Gate 1 fails on them; this column is here so\n")
	b.WriteString("the page cannot quietly disagree with the gate.\n\n")

	b.WriteString("| Model | Elements | Extrude | Brep | OBB | Empty | OBB rate | Collapsed | AABB ratio p50 | p90 | max |\n")
	b.WriteString("|---|---|---|---|---|---|---|---|---|---|---|\n")
	covs := make(map[string]Coverage, len(Public))
	for _, name := range Public {
		c, err := MeasureCoverage(name)
		if err != nil {
			return "", err
		}
		covs[name] = c
		l, err := MeasureLooseness(name)
		if err != nil {
			return "", err
		}
		fmt.Fprintf(&b, "| `%s` | %d | %d | %d | %d | %d | %.1f%% | %d | %.4f | %.4f | %.4f |\n",
			name, c.Total, c.Extrude, c.Brep, c.OBB, c.Empty, 100*OBBRate(c), l.Collapsed, l.P50, l.P90, l.Max)
	}

	totals := map[string]int{}
	perModel := map[string]int{}
	for _, name := range Public {
		f, err := Load(name)
		if err != nil {
			return "", err
		}
		r, err := model.Extract(f)
		if err != nil {
			return "", fmt.Errorf("parity: extract %s: %w", name, err)
		}
		for ty, n := range geometry.UnhandledItemTypes(f, r) {
			totals[ty] += n
			perModel[name] += n
		}
	}

	b.WriteString("\n## What falls back, and how often\n\n")
	b.WriteString("Representation-item types that have no tessellation path at all. ")
	b.WriteString("Closing the top of this list buys the most accuracy.\n\n")
	b.WriteString("Counts are OCCURRENCES, not distinct entities: an `IfcMappedItem`\n")
	b.WriteString("is resolved to the items it maps, and each resolution is counted\n")
	b.WriteString("again — once per element that reaches it. A family placed many\n")
	b.WriteString("times via one `IfcRepresentationMap` costs accuracy every time it\n")
	b.WriteString("is placed, so it must rank every time, not once. This means a\n")
	b.WriteString("type's count can legitimately exceed the number of entities of\n")
	b.WriteString("that type in the file. Keys are the upper-case STEP keyword as parsed\n")
	b.WriteString("(`IFCFACEBASEDSURFACEMODEL`, not `IfcFaceBasedSurfaceModel`);\n")
	b.WriteString("nothing here changes that casing.\n\n")

	b.WriteString("**Occurrences here and the OBB column above are different\n")
	b.WriteString("quantities, and neither converts into the other.** This table\n")
	b.WriteString("counts representation ITEMS, once per element that reaches one;\n")
	b.WriteString("the OBB column counts ELEMENTS. Two different units: where a\n")
	b.WriteString("model's two figures land close together that is coincidence, not\n")
	b.WriteString("agreement. Do not subtract them.\n\n")

	b.WriteString("**This list is also not exhaustive of what falls back.** It names\n")
	b.WriteString("only types that `tessellateItemDepth` has no case for at all,\n")
	b.WriteString("looking through the two wrappers that would otherwise hide one —\n")
	b.WriteString("an `IfcMappedItem` is resolved to the items it maps, and a boolean\n")
	b.WriteString("to its operands. An element becomes a box just as readily when a\n")
	b.WriteString("dispatched path IS attempted and declines partway: an extrusion\n")
	b.WriteString("whose profile cannot be built, a brep whose shell cannot be\n")
	b.WriteString("closed. None of that class appears here. Nor do presentation entities\n")
	b.WriteString("(`IfcStyledItem` and the like), which this diagnostic excludes as\n")
	b.WriteString("appearance rather than shape so a colour assignment cannot outrank\n")
	b.WriteString("a missing solid — they still reach the same fallback, so if one\n")
	b.WriteString("ever does yield a box this list will not name it either. So a\n")
	b.WriteString("type's absence from this table is not evidence that it never\n")
	b.WriteString("falls back, and the counts below are a lower bound on the causes.\n\n")

	b.WriteString(unattributedNote(covs, perModel))

	b.WriteString("| Item type | Occurrences |\n|---|---|\n")

	types := make([]string, 0, len(totals))
	for ty := range totals {
		types = append(types, ty)
	}
	sort.Slice(types, func(i, j int) bool {
		if totals[types[i]] != totals[types[j]] {
			return totals[types[i]] > totals[types[j]]
		}
		return types[i] < types[j]
	})
	if len(types) == 0 {
		b.WriteString("| _none_ | 0 |\n")
	}
	for _, ty := range types {
		fmt.Fprintf(&b, "| `%s` | %d |\n", ty, totals[ty])
	}

	b.WriteString("\n## Known Gate 1 violations\n\n")
	b.WriteString("Gate 1 asserts that goifc's AABB contains IfcOpenShell's oracle box\n")
	b.WriteString("for every element the oracle and goifc's scene both know. A bound\n")
	b.WriteString("that under-reports is always a bug, never a legitimate fallback —\n")
	b.WriteString("an OBB fallback box is allowed to be larger than the solid it\n")
	b.WriteString("stands for, never smaller.\n")
	b.WriteString("The violations below are real, currently open goifc geometry gaps,\n")
	b.WriteString("tracked in `parity/knownviolations.go`'s `knownViolations` allowlist\n")
	b.WriteString("so CI stays green on this known state while still failing on any\n")
	b.WriteString("new or worsened violation.\n\n")

	fmt.Fprintf(&b, "Across the public corpus the gate compares %d elements, of which %d\n%s contained.\n\n",
		totalCompared, totalContained, pluralAre(totalContained))

	for _, name := range Public {
		g := per[name]
		kvs := knownViolations[name]
		if g.compared == g.contained {
			fmt.Fprintf(&b, "Against `%s`, the gate compares %d elements, and all %d %s contained.\n\n",
				name, g.compared, g.contained, pluralAre(g.contained))
			continue
		}
		short := g.compared - g.contained
		fmt.Fprintf(&b, "Against `%s`, the gate compares %d elements. %d %s contained; %d %s\nnot:\n\n",
			name, g.compared, g.contained, pluralAre(g.contained), short, pluralAre(short))
		if len(kvs) == 0 {
			b.WriteString("None of them is in the `knownViolations` allowlist, which means Gate 1\nis failing and this page was regenerated in a state that must not be\ncommitted.\n\n")
			continue
		}
		b.WriteString("| GlobalID | Axis | Shortfall | What it is |\n|---|---|---|---|\n")
		for _, kv := range kvs {
			fmt.Fprintf(&b, "| `%s` | %s | %.9f m | %s |\n", kv.globalID, kv.axis, kv.shortfall, kv.note)
		}
		b.WriteString("\n")
	}

	return b.String(), nil
}

// pluralAre returns the correctly-inflected copula for n, so "1 is contained"
// reads right alongside "2 are contained".
func pluralAre(n int) string {
	if n == 1 {
		return "is"
	}
	return "are"
}

// pluralS returns "" for one and "s" for any other count.
func pluralS(n int) string {
	if n == 1 {
		return ""
	}
	return "s"
}

// unattributedNote names, from the measurements themselves, every model whose
// OBB fallbacks the gap table attributes to nothing at all: a model with
// fallback elements but no unhandled item type has every one of its fallbacks
// caused by a dispatched path that declined mid-attempt, which
// geometry.UnhandledItemTypes cannot see (the cause is inference; the lack of
// attribution is measured). Derived rather than written down, so
// it cannot outlive the measurement it describes.
// gate1 is one model's measured Gate 1 outcome.
type gate1 struct{ compared, contained int }

// measureGate1 runs Gate 1's own assertion over the public corpus and returns
// the per-model and total counts.
//
// The compared count is the INTERSECTION of the oracle and goifc's scene, not
// the oracle's size: an element the oracle knows but goifc's scene does not is
// never compared, and printing len(oracle) would overstate what the gate
// actually checked. Containment is measured here rather than inferred from the
// allowlist's length, so every published figure — the totals, the per-model
// sentences, and the count of shortfalls in the header prose — is the same
// assertion Gate 1 makes rather than an arithmetic restatement of the
// allowlist, which can hold an entry for an element no longer in the scene.
func measureGate1() (map[string]gate1, int, int, error) {
	var totalCompared, totalContained int
	per := make(map[string]gate1, len(Public))
	for _, name := range Public {
		oracle, err := LoadOracle(name)
		if err != nil {
			return nil, 0, 0, err
		}
		sc, err := SceneOf(name)
		if err != nil {
			return nil, 0, 0, err
		}
		var g gate1
		for _, e := range sc.Elements {
			want, ok := oracle[e.GlobalID]
			if !ok {
				continue
			}
			g.compared++
			if Contains(ElementBox(e), want, Tolerance) {
				g.contained++
			}
		}
		per[name] = g
		totalCompared += g.compared
		totalContained += g.contained
	}
	return per, totalCompared, totalContained, nil
}

func unattributedNote(covs map[string]Coverage, perModel map[string]int) string {
	var names []string
	for _, name := range Public {
		if covs[name].OBB > 0 && perModel[name] == 0 {
			names = append(names, name)
		}
	}
	if len(names) == 0 {
		return "In this corpus, every model that has a fallback element also reports\nat least one unhandled item type below.\n\n"
	}
	var b strings.Builder
	b.WriteString("Concretely, in this corpus:\n\n")
	for _, name := range names {
		n := covs[name].OBB
		fmt.Fprintf(&b, "- `%s` has %d OBB element%s and reports no unhandled item type at\n", name, n, pluralS(n))
		b.WriteString("  all, so nothing in the table below accounts for a single one of\n")
		b.WriteString("  them. What caused them is invisible to this diagnostic by\n")
		b.WriteString("  construction — most likely a dispatched path that declined\n")
		b.WriteString("  mid-attempt.\n")
	}
	b.WriteString("\n")
	return b.String()
}
